crud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # jobs로 들어왔다면 jobs/urls.py로 이동해
    path('jobs/', include('jobs.urls')),

    # articles로 들어왔다면 articles/urls.py로 이동해
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    # static('/media/', BASE_DIR/media),

    path('questions/', include('questions.urls')),
]

# 사용자가 미디어 파일이 있는 곳으로 올 수 있는 경로를 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
#특정뷰함수와 매핑해주는 파일
from django.urls import path
from . import views


app_name = 'questions'
# /articles/ __
urlpatterns = [
    path('', views.index, name='index'),
    path('vote/', views.vote, name='vote'),
    # path('<int:article_pk>/', views.detail, name='detail'),
    # # path('new/', views.new, name='new'),
    # # create로 들어갈거라서 new는 없앰 - 하나로 합칠거임
    # path('create/', views.create, name='create'),
    # # /articles/4/delete/
    # path('<int:article_pk>/delete/',views.delete, name='delete'),
    # path('<int:article_pk>/update/', views.update, name='update'),
    # path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    # path('<int:article_pk>/<int:comment_pk>/comments_delete/', views.comments_delete, name='comments_delete'),
    # path('selected/', views.selected, name='selected'),
]

questions/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=20)

class Choice(models.Model):
    # on_delete=models.CASCADE == 'Article이 삭제되면 Comment도 함께 삭제'
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    content = models.CharField(max_length=20)
    votes = models.IntegerField()

questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Question, Choice

# Create your views here.
def index(request):
    question = Question.objects.all()

    context = {'question': question}
    return render(request, 'questions/index.html', context)

def vote(request):
    question = Question.objects.get(pk=1)
    select = request.POST.get('selected')
    choice = Choice.objects.get(content=select)
    choice.votes += 1
    choice.save()
    choices = question.choice_set.all()
    context = {
        'question': question,
        'choices': choices,
    }

    return render(request, 'questions/vote.html', context)

questions/templates/questions/index.html
{% extends 'base.html' %}

{% block title %}Questions{% endblock title %}

{% block body %}
  <h1>회식메뉴추천</h1>
  <h1>{{ question.title }}</h1>
  <form action="{% url 'questions:vote' %}" method="POST" >
    {% csrf_token %}
    <select name="selected">
      <option value="한식">한식</option>
      <option value="중식">중식</option>
      <option value="양식">양식</option>
    </select>
    <button type="sumbit">제출</button>
  </form>
{% endblock body %}

questions/templates/questions/vote.html
{% extends 'base.html' %}

{% block title %}Vote{% endblock title %}

{% block body %}
  <h1>{{ question.title }}</h1>

  {% for choice in choices %}
    <p>{{ choice.content }} : {{ choice.votes }}</p>
  {% endfor %}
  <a href="{% url 'questions:index' %}">[돌아가기]</a>
  
{% endblock body %}