articles/urls.py
#특정뷰함수와 매핑해주는 파일
from django.urls import path
from . import views


app_name = 'articles'
# /articles/ __
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    # path('new/', views.new, name='new'),
    # create로 들어갈거라서 new는 없앰 - 하나로 합칠거임
    path('create/', views.create, name='create'),
    # /articles/4/delete/
    path('<int:article_pk>/delete/',views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/<int:comment_pk>/comments_delete/', views.comments_delete, name='comments_delete'),
    path('selected/', views.selected, name='selected'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # jobs로 들어왔다면 jobs/urls.py로 이동해
    path('jobs/', include('jobs.urls')),

    # articles로 들어왔다면 articles/urls.py로 이동해
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    # static('/media/', BASE_DIR/media),

    path('questions/', include('questions.urls')),
]

# 사용자가 미디어 파일이 있는 곳으로 올 수 있는 경로를 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.processors import Thumbnail
from imagekit.models import ImageSpecField

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField() # 문자열 빈 값 저장은 null=True 하지 말기
    
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,200)],
        format='JPEG',
        options={'quality':90},
    )
    # blank: 데이터 유효성과 관련되어있다
    # null: DB와 관련되어 있다.
    # '', Null
    created_at = models.DateTimeField(auto_now_add=True)        # 이거중요
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
   # on_delete=models.CASCADE == 'Article이 삭제되면 Comment도 함께 삭제'
   article = models.ForeignKey(Article, on_delete=models.CASCADE)
   content = models.CharField(max_length=200)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)
   class Meta:
       ordering = ['-pk']
   def __str__(self):
       return self.content

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment

# Create your views here.

# articles 의 메인페이지, articles list 를 보여줌
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

# variable routing으로 사용자가 보기를 원하는 페이지 pk를 받아서
# detail 페이지를 보여준다.
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    comments = article.comment_set.all()

    context = {
        'article':article,
        'comments':comments,
        }
    return render(request, 'articles/detail.html', context)

# 입력페이지 제공
# GET /articles/create/ - 이경우에는 페이지만 받아가는것
# def new(request):
#     embed()
#     return render(request, 'articles/new.html')
    

# 데이터를 전달받아서 article 생성
# POST /articels/create 
def create(request):
    
    # 만약 POST요청으로 사용자 데이터 받아서 article 생성
    # /articles/new/ 의 new.html 의 form 에서 전달받은 데이터들
    if request.method == 'POST':
        title = request.POST.get('title') # 데이터 따오기
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)
        # article.title = title
        # article.content = content
        article.save()
        # return render(request, 'articles/create.html')
    
        return redirect('articles:detail',article.pk)

    # 만약 GET요청으로 들어오면 html페이지 rendering
    else:
        return render(request, 'articles/create.html')

# 사용자로부터 받은 article_pk값에 해당하는 article을 삭제한다.
def delete(request, article_pk):
    article = get_object_or_404(Article, pk = article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article_pk)

def update(request, article_pk):
    # POST : 실제 update 로직이 수행
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        if image:
            article.image = image
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)
    # GET : update를 하기 위한 Form 을 제공하는 페이지
    else:
        
        context = {'article':article}
        return render(request,'articles/update.html', context)

def comments_create(request, article_pk):
    # article_pk에 해당하는 article에 새로운 comment 생성
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()
        comment.content = content
        comment.article = article
        comment.save()
    # 생성한 다음 article detail page로 redirect
        return redirect('articles:detail', article.pk)
    

def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

def selected(request):
    chks = request.POST.getlist('chk')
    for chk in chks:
        article = Article.objects.get(pk=chk)
        article.delete()
    return redirect('articles:index')

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title"><br/>
    <textarea name="content" cols="30" rows="10"></textarea><br/>
    <label for="image">이미지:</label>
    <input type="file" name="image" id="image" accept="image/*"><br/>
    <button type="submit">생성하기</button>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
  </form>
{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article Detail{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자 : {{ article.created_at }}</p>
  <hr>
  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <p>{{ article.content }}</p>

  <hr>
  <h4>Comments</h4>
  {% comment %} 댓글작성을 위한 form {% endcomment %}
  <form action="{% url 'articles:comments_create' article.pk %}" method = "POST">
    {% csrf_token %}
    <input type="text" name="content">
    <button type="submit">댓글작성</button>
  </form>
  <ul>
  {% for comment in comments %}
    <li>{{ comment.content }}</li>
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method = "POST">
      {% csrf_token %}
      <button type="submit">삭제하기</button>
    </form>
    {% empty %}
    <p>아직댓글이 없습니다.</p>
  {% endfor %}
  </ul>
  
  
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method='POST' onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    <button type="submit">삭제하기</button>
  </form>

{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Articles{% endblock title %}

{% block body %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>
  <img src=" {% static 'articles/images/apeach.jpg' %}" alt="">
  <hr>
  <form action="{% url 'articles:selected' %}" method="POST">
    {% csrf_token %}
    {% for article in articles %}
    <div>
      {% if article.image %}
        <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image_thumbnail }}">
      {% endif %}
      <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
      <p>{{ article.content }}</p>
      <input type="checkbox" name="chk" value="{{ article.pk }}">
    </div>
    <br>
    {% endfor %}
    <button type="submit">삭제하기</button>
    <hr>
  </form>
{% endblock body %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}" method="POST/GET">
    <input type="text" name="title"><br/>
    <textarea name="content" cols="30" rows="10"></textarea><br/>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% block title %}Update Article{% endblock title %}
{% block body %}
<h1>Update Article</h1>
{% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image }}">
{% endif %}
<form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
 <input type="text" name="title" value="{{ article.title }}"><br>
 <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br>
 <label for="image">이미지: </label>
 <input type="file" name="image" id="image"><br>
 <button type="submit">수정하기</button>
</form>
<a href="{% url 'articles:detail' article.pk %}">뒤로가기</a>
{% endblock body %}