crud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # jobs로 들어왔다면 jobs/urls.py로 이동해
    path('jobs/', include('jobs.urls')),

    # articles로 들어왔다면 articles/urls.py로 이동해
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    # static('/media/', BASE_DIR/media),

    path('questions/', include('questions.urls')),
]

# 사용자가 미디어 파일이 있는 곳으로 올 수 있는 경로를 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views


app_name = 'jobs'
# /articles/ __
urlpatterns = [
    path('', views.index, name='index'),
    path('past_job/', views.past_job, name='past_job'),
]

jobs/models.py
from django.db import models

# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=20)
    profile_image = models.ImageField(blank=True)
    past_job = models.TextField()

    def __str__(self):
        return self.name

jobs/views.py
from django.shortcuts import render
from .models import Job
from faker import Faker
import requests
from pprint import pprint
fake = Faker()
URL = 'https://api.giphy.com/v1/gifs/search?api_key=oXnLi6GHlDqjY24l1fHOpZJv90RXZPuN&limit=1&lang=en&q='

# Create your views here.

def index(request):
    return render(request, 'jobs/index.html')


def past_job(request):

    name = request.POST.get('name')
    image = request.FILES.get('image')      ##### 여기
    
    if Job.objects.filter(name=name):
        job = Job.objects.get(name=name)
    else:
        job = Job()
        job.name = name
        job.past_job = fake.job()
        job.profile_image = image
        job.save()

    url = URL + job.past_job
    data = requests.get(url).json()

    try:
        data = data.get('data')[0].get('images').get('downsized').get('url')
    except:
        data = 'Random'
    
    context = {
        'job':job,
        'data': data,
        }
        
    # context = {'past_jobs':past_jobs}
    return render(request, 'jobs/past_job.html', context)

jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block title %}Jobs{% endblock title %}

{% block body %}
  <h1>전생 직업 찾기</h1>
  <form action="{% url 'jobs:past_job' %}" method= "POST" enctype="multipart/form-data">
  {% csrf_token %}
    <input type="text" name="name"><br>
    <label for="image">이미지:</label>
    <input type="file" name="image" id="image" accept="image/*"><br/>
    <button type="submit">보내기</button>
  </form>
{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}

{% block title %}Past Job{% endblock title %}

{% block body %}
  <h1>{{ job.past_job }}</h1>
  <img src="{{ data }}" alt=""><br>
  {% if job.profile_image %}
  <img src="{{ job.profile_image.url }}" alt="">
  {% endif %}
  
  <a href="{% url 'jobs:index' %}">[뒤로가기]</a>
{% endblock body %}